# This was generated using generate_quick_test_docker
FROM ubuntu:14.04
RUN apt-get update
RUN apt-get install -y python-setuptools python-dev gcc
RUN easy_install pip
RUN pip install requests python-digitalocean pycrypto docopt paramiko
