language: python

python:
  - "2.7"

install:
  - docker login --email=$DOCKER_EMAIL --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
  - "pip install -r requirements.txt"

script: fab ci

services:
  - docker

cache:
  directories:
    - $HOME/.cache/pip
